SNO-158-create-minimally-indexed-deploy
ENCODE-DCC/snovault pull request #276
Opened 2020-06-30 23:33 UTC by keenangraham

2020-07-02 01:04 UTC, hitz approved these changes

2021-01-25 21:45 UTC, paul-sud requested changes
One change requested. Test failure is not related to this ticket.

2021-01-25 21:45 UTC, paul-sud commented on src/snovault/util.py
> +            for uuid in f.readlines()
The `readlines` is not necessary:
```suggestion
            for uuid in f
```

2021-01-25 22:02 UTC, keenangraham commented
Thanks, updated.

2021-01-25 22:04 UTC, paul-sud approved these changes

2021-02-04 02:34 UTC, merged